export const postData = {
  user: {
    name: '익명의 사용자',
    avatar: 'https://via.placeholder.com/150/000000/FFFFFF/?text=User'
  },
  content: '오늘 정말 최악의 하루였어... 무슨 말을 해야 할지 모르겠다.',
  comments: [
    // 500개 댓글, 선플 25개는 모두 다른 내용으로 작성, 전체적으로 무작위로 섞음
    { id: 1, user: 'User1', text: '이런 글 올릴 시간에 잠이나 자라.', isGood: false },
    { id: 2, user: 'User2', text: '오늘은 힘들었겠지만 내일은 분명 더 나아질 거예요.', isGood: true },
    { id: 3, user: 'User3', text: '또 징징거림? 지겹다.', isGood: false },
    { id: 4, user: 'User4', text: '당신이 여기 있다는 것만으로도 큰 의미가 있어요.', isGood: true },
    { id: 5, user: 'User5', text: '누가 신경이나 쓴다고 생각해?', isGood: false },
    { id: 6, user: 'User6', text: '당신의 작은 용기가 누군가에겐 큰 힘이 됩니다.', isGood: true },
    { id: 7, user: 'User7', text: '이런 글 볼 때마다 짜증난다.', isGood: false },
    { id: 8, user: 'User8', text: '오늘도 스스로를 칭찬해 주세요. 충분히 잘하고 있어요.', isGood: true },
    { id: 9, user: 'User9', text: '또 시작이네.', isGood: false },
    { id: 10, user: 'User10', text: '당신의 이야기를 들어줄 사람이 분명 있을 거예요.', isGood: true },
    { id: 11, user: 'User11', text: '관심받고 싶어서 이러는 거지?', isGood: false },
    { id: 12, user: 'User12', text: '오늘 하루도 무사히 버틴 당신이 자랑스러워요.', isGood: true },
    { id: 13, user: 'User13', text: '이런 글 올리지 마라.', isGood: false },
    { id: 14, user: 'User14', text: '당신의 감정은 부끄러운 게 아니에요.', isGood: true },
    { id: 15, user: 'User15', text: '또 징징대네.', isGood: false },
    { id: 16, user: 'User16', text: '당신이 힘들 때 곁에 있어줄 사람이 꼭 있을 거예요.', isGood: true },
    { id: 17, user: 'User17', text: '이런 글 그만 좀 써라.', isGood: false },
    { id: 18, user: 'User18', text: '당신의 존재는 이 세상에 꼭 필요해요.', isGood: true },
    { id: 19, user: 'User19', text: '누가 이런 글에 공감하냐?', isGood: false },
    { id: 20, user: 'User20', text: '오늘 힘들었더라도 내일은 분명 웃을 수 있을 거예요.', isGood: true },
    { id: 21, user: 'User21', text: '또 이런 글이네.', isGood: false },
    { id: 22, user: 'User22', text: '당신의 선택을 응원합니다. 포기하지 마세요.', isGood: true },
    { id: 23, user: 'User23', text: '이런 글 올릴 시간에 운동이나 해라.', isGood: false },
    { id: 24, user: 'User24', text: '오늘도 잘 견뎌줘서 고마워요. 당신은 소중해요.', isGood: true },
    { id: 25, user: 'User25', text: '또 징징거림? 한심하다.', isGood: false },
    { id: 26, user: 'User26', text: '당신이 느끼는 감정은 모두 소중합니다.', isGood: true },
    { id: 27, user: 'User27', text: '이런 글 보기 싫다. 삭제 좀.', isGood: false },
    { id: 28, user: 'User28', text: '당신의 노력이 헛되지 않길 진심으로 바랍니다.', isGood: true },
    { id: 29, user: 'User29', text: '관심받고 싶어서 글 올렸네 ㅋㅋㅋ', isGood: false },
    { id: 30, user: 'User30', text: '오늘은 울어도 괜찮아요. 내일은 더 나아질 거예요.', isGood: true },
    { id: 31, user: 'User31', text: '이런 글 올릴 시간에 공부나 해라.', isGood: false },
    { id: 32, user: 'User32', text: '당신의 하루가 평안하길 진심으로 기도할게요.', isGood: true },
    { id: 33, user: 'User33', text: '또 시작이네.', isGood: false },
    { id: 34, user: 'User34', text: '당신이 여기 있다는 것만으로도 위로가 됩니다.', isGood: true },
    { id: 35, user: 'User35', text: '누가 신경이나 쓴다고.', isGood: false },
    { id: 36, user: 'User36', text: '세상에는 당신을 응원하는 사람이 분명히 있어요.', isGood: true },
    { id: 37, user: 'User37', text: '이런 글 볼 때마다 짜증난다.', isGood: false },
    { id: 38, user: 'User38', text: '울고 싶을 땐 참지 말고 울어도 돼요.', isGood: true },
    { id: 39, user: 'User39', text: '또 징징거림? 지겹다.', isGood: false },
    { id: 40, user: 'User40', text: '당신의 행복을 진심으로 기원합니다.', isGood: true },
    { id: 41, user: 'User41', text: '이런 글 올리지 마라.', isGood: false },
    { id: 42, user: 'User42', text: '오늘도 잘 견뎌줘서 고마워요. 내일은 더 행복하길.', isGood: true },
    { id: 43, user: 'User43', text: '또 징징거림? 한심하다.', isGood: false },
    { id: 44, user: 'User44', text: '오늘도 당신을 응원하는 사람이 있습니다.', isGood: true },
    { id: 45, user: 'User45', text: '누가 이런 글에 공감하냐?', isGood: false },
    { id: 46, user: 'User46', text: '당신의 감정은 소중하니 부끄러워하지 마세요.', isGood: true },
    { id: 47, user: 'User47', text: '또 이런 글이네.', isGood: false },
    { id: 48, user: 'User48', text: '당신의 선택이 옳았음을 언젠가 알게 될 거예요.', isGood: true },
    { id: 49, user: 'User49', text: '이런 글 올릴 시간에 운동이나 해라.', isGood: false },
    { id: 50, user: 'User50', text: '오늘 하루도 수고 많았어요. 내일은 더 좋은 일이 있을 거예요.', isGood: true },
    // 51~500: 기존과 동일하게 유지
    { id: 51, user: 'User51', text: '뭐 그런 걸로 힘들어하냐? 멘탈이 두부임?', isGood: false },
    { id: 52, user: 'User52', text: '힘내세요! 당신은 혼자가 아니에요. 주변에 좋은 사람들이 더 많을 거예요.', isGood: false },
    { id: 53, user: 'User53', text: '관심받고 싶어서 글 올렸네 ㅋㅋㅋ', isGood: false },
    { id: 54, user: 'User54', text: '이런 글 보기 싫다. 삭제 좀.', isGood: false },
    { id: 55, user: 'User55', text: '무슨 일인지는 모르겠지만, 분명 잘 해결될 거예요. 응원합니다!', isGood: false },
    { id: 56, user: 'User56', text: 'ㅋㅋㅋㅋㅋ 한심하다', isGood: false },
    { id: 57, user: 'User57', text: '당신의 존재는 그 자체로 소중해요. 잊지 마세요.', isGood: false },
    { id: 58, user: 'User58', text: '에휴...ㅉㅉ', isGood: false },
    { id: 59, user: 'User59', text: '이런 거 올릴 시간에 자기계발이나 더 하지?', isGood: false },
    { id: 60, user: 'User60', text: '따뜻한 차 한잔 하면서 마음을 진정시켜보세요. 괜찮아질 거예요.', isGood: false },
    { id: 61, user: 'User61', text: '다 너가 잘못해서 그런거 아님?', isGood: false },
    { id: 62, user: 'User62', text: '세상에는 당신의 행복을 바라는 사람들이 더 많아요.', isGood: false },
    { id: 63, user: 'User63', text: '울고싶을 때는 실컷 우는 것도 방법이에요. 감정을 억누르지 마세요.', isGood: false },
    { id: 64, user: 'User64', text: '그렇게 쉽게 상처받으면 앞으로 어떻게 살래?', isGood: false },
    { id: 65, user: 'User65', text: '오늘 하루도 고생 많았어요. 맛있는 거 먹고 푹 쉬어요!', isGood: false },
    { id: 66, user: 'User66', text: '이런 글 올릴 시간에 공부나 해라.', isGood: false },
    { id: 67, user: 'User67', text: '당신의 용기에 박수를 보냅니다.', isGood: false },
    { id: 68, user: 'User68', text: '또 징징대네.', isGood: false },
    { id: 69, user: 'User69', text: '당신은 충분히 잘하고 있어요.', isGood: false },
    { id: 70, user: 'User70', text: '이런 글 그만 좀 써라.', isGood: false },
    { id: 71, user: 'User71', text: '오늘도 힘내요! 응원할게요.', isGood: false },
    { id: 72, user: 'User72', text: '관심받고 싶어서 이러는 거지?', isGood: false },
    { id: 73, user: 'User73', text: '당신의 하루가 더 좋아지길 바랍니다.', isGood: false },
    { id: 74, user: 'User74', text: '이런 글 볼 때마다 짜증난다.', isGood: false },
    { id: 75, user: 'User75', text: '당신은 혼자가 아니에요.', isGood: false },
    { id: 76, user: 'User76', text: '또 시작이네.', isGood: false },
    { id: 77, user: 'User77', text: '당신의 마음을 이해해요.', isGood: false },
    { id: 78, user: 'User78', text: '이런 글 올리지 마라.', isGood: false },
    { id: 79, user: 'User79', text: '당신의 용기가 멋져요.', isGood: false },
    { id: 80, user: 'User80', text: '누가 신경이나 쓴다고.', isGood: false },
    { id: 81, user: 'User81', text: '당신은 소중한 사람이에요.', isGood: false },
    { id: 82, user: 'User82', text: '또 징징거림?', isGood: false },
    { id: 83, user: 'User83', text: '당신의 이야기를 들어줄게요.', isGood: false },
    { id: 84, user: 'User84', text: '이런 글 올릴 시간에 일이나 해라.', isGood: false },
    { id: 85, user: 'User85', text: '당신의 존재가 큰 힘이 됩니다.', isGood: false },
    { id: 86, user: 'User86', text: '또 이런 글이네.', isGood: false },
    { id: 87, user: 'User87', text: '당신은 충분히 멋져요.', isGood: false },
    { id: 88, user: 'User88', text: '누가 신경이나 쓴다고 생각해?', isGood: false },
    { id: 89, user: 'User89', text: '당신의 하루가 행복하길.', isGood: false },
    { id: 90, user: 'User90', text: '이런 글 올릴 시간에 운동이나 해라.', isGood: false },
    { id: 91, user: 'User91', text: '당신은 혼자가 아니에요.', isGood: false },
    { id: 92, user: 'User92', text: '또 징징대네.', isGood: false },
    { id: 93, user: 'User93', text: '당신의 용기에 박수를 보냅니다.', isGood: false },
    { id: 94, user: 'User94', text: '이런 글 그만 좀 써라.', isGood: false },
    { id: 95, user: 'User95', text: '오늘도 힘내요! 응원할게요.', isGood: false },
    { id: 96, user: 'User96', text: '관심받고 싶어서 이러는 거지?', isGood: false },
    { id: 97, user: 'User97', text: '당신의 하루가 더 좋아지길 바랍니다.', isGood: false },
    { id: 98, user: 'User98', text: '이런 글 볼 때마다 짜증난다.', isGood: false },
    { id: 99, user: 'User99', text: '당신은 혼자가 아니에요.', isGood: false },
    { id: 100, user: 'User100', text: '또 시작이네.', isGood: false },
    { id: 101, user: 'User101', text: '당신의 마음을 이해해요.', isGood: false },
    { id: 102, user: 'User102', text: '이런 글 올리지 마라.', isGood: false },
    { id: 103, user: 'User103', text: '당신의 용기가 멋져요.', isGood: false },
    { id: 104, user: 'User104', text: '누가 신경이나 쓴다고.', isGood: false },
    { id: 105, user: 'User105', text: '당신은 소중한 사람이에요.', isGood: false },
    { id: 106, user: 'User106', text: '또 징징거림?', isGood: false },
    { id: 107, user: 'User107', text: '당신의 이야기를 들어줄게요.', isGood: false },
    { id: 108, user: 'User108', text: '이런 글 올릴 시간에 일이나 해라.', isGood: false },
    { id: 109, user: 'User109', text: '당신의 존재가 큰 힘이 됩니다.', isGood: false },
    { id: 110, user: 'User110', text: '또 이런 글이네.', isGood: false },
    { id: 111, user: 'User111', text: '당신은 충분히 멋져요.', isGood: false },
    { id: 112, user: 'User112', text: '누가 신경이나 쓴다고 생각해?', isGood: false },
    { id: 113, user: 'User113', text: '당신의 하루가 행복하길.', isGood: false },
    { id: 114, user: 'User114', text: '이런 글 올릴 시간에 운동이나 해라.', isGood: false },
    { id: 115, user: 'User115', text: '당신은 혼자가 아니에요.', isGood: false },
    { id: 116, user: 'User116', text: '또 징징대네.', isGood: false },
    { id: 117, user: 'User117', text: '당신의 용기에 박수를 보냅니다.', isGood: false },
    { id: 118, user: 'User118', text: '이런 글 그만 좀 써라.', isGood: false },
    { id: 119, user: 'User119', text: '오늘도 힘내요! 응원할게요.', isGood: false },
    { id: 120, user: 'User120', text: '관심받고 싶어서 이러는 거지?', isGood: false },
    { id: 121, user: 'User121', text: '당신의 하루가 더 좋아지길 바랍니다.', isGood: false },
    { id: 122, user: 'User122', text: '이런 글 볼 때마다 짜증난다.', isGood: false },
    { id: 123, user: 'User123', text: '당신은 혼자가 아니에요.', isGood: false },
    { id: 124, user: 'User124', text: '또 시작이네.', isGood: false },
    { id: 125, user: 'User125', text: '당신의 마음을 이해해요.', isGood: false },
    { id: 126, user: 'User126', text: '이런 글 올리지 마라.', isGood: false },
    { id: 127, user: 'User127', text: '당신의 용기가 멋져요.', isGood: false },
    { id: 128, user: 'User128', text: '누가 신경이나 쓴다고.', isGood: false },
    { id: 129, user: 'User129', text: '당신은 소중한 사람이에요.', isGood: false },
    { id: 130, user: 'User130', text: '또 징징거림?', isGood: false },
    { id: 131, user: 'User131', text: '당신의 이야기를 들어줄게요.', isGood: false },
    { id: 132, user: 'User132', text: '이런 글 올릴 시간에 일이나 해라.', isGood: false },
    { id: 133, user: 'User133', text: '당신의 존재가 큰 힘이 됩니다.', isGood: false },
    { id: 134, user: 'User134', text: '또 이런 글이네.', isGood: false },
    { id: 135, user: 'User135', text: '당신은 충분히 멋져요.', isGood: false },
    { id: 136, user: 'User136', text: '누가 신경이나 쓴다고 생각해?', isGood: false },
    { id: 137, user: 'User137', text: '당신의 하루가 행복하길.', isGood: false },
    { id: 138, user: 'User138', text: '이런 글 올릴 시간에 운동이나 해라.', isGood: false },
    { id: 139, user: 'User139', text: '당신은 혼자가 아니에요.', isGood: false },
    { id: 140, user: 'User140', text: '또 징징대네.', isGood: false },
    { id: 141, user: 'User141', text: '당신의 용기에 박수를 보냅니다.', isGood: false },
    { id: 142, user: 'User142', text: '이런 글 그만 좀 써라.', isGood: false },
    { id: 143, user: 'User143', text: '오늘도 힘내요! 응원할게요.', isGood: false },
    { id: 144, user: 'User144', text: '관심받고 싶어서 이러는 거지?', isGood: false },
    { id: 145, user: 'User145', text: '당신의 하루가 더 좋아지길 바랍니다.', isGood: false },
    { id: 146, user: 'User146', text: '이런 글 볼 때마다 짜증난다.', isGood: false },
    { id: 147, user: 'User147', text: '당신은 혼자가 아니에요.', isGood: false },
    { id: 148, user: 'User148', text: '또 시작이네.', isGood: false },
    { id: 149, user: 'User149', text: '당신의 마음을 이해해요.', isGood: false },
    { id: 150, user: 'User150', text: '이런 글 올리지 마라.', isGood: false },
    { id: 151, user: 'User151', text: '뭐 그런 걸로 힘들어하냐? 멘탈이 두부임?', isGood: false },
    { id: 152, user: 'User152', text: '힘내세요! 당신은 혼자가 아니에요. 주변에 좋은 사람들이 더 많을 거예요.', isGood: false },
    { id: 153, user: 'User153', text: '관심받고 싶어서 글 올렸네 ㅋㅋㅋ', isGood: false },
    { id: 154, user: 'User154', text: '이런 글 보기 싫다. 삭제 좀.', isGood: false },
    { id: 155, user: 'User155', text: '무슨 일인지는 모르겠지만, 분명 잘 해결될 거예요. 응원합니다!', isGood: false },
    { id: 156, user: 'User156', text: 'ㅋㅋㅋㅋㅋ 한심하다', isGood: false },
    { id: 157, user: 'User157', text: '당신의 존재는 그 자체로 소중해요. 잊지 마세요.', isGood: false },
    { id: 158, user: 'User158', text: '에휴...ㅉㅉ', isGood: false },
    { id: 159, user: 'User159', text: '이런 거 올릴 시간에 자기계발이나 더 하지?', isGood: false },
    { id: 160, user: 'User160', text: '따뜻한 차 한잔 하면서 마음을 진정시켜보세요. 괜찮아질 거예요.', isGood: false },
    { id: 161, user: 'User161', text: '다 너가 잘못해서 그런거 아님?', isGood: false },
    { id: 162, user: 'User162', text: '세상에는 당신의 행복을 바라는 사람들이 더 많아요.', isGood: false },
    { id: 163, user: 'User163', text: '울고싶을 때는 실컷 우는 것도 방법이에요. 감정을 억누르지 마세요.', isGood: false },
    { id: 164, user: 'User164', text: '그렇게 쉽게 상처받으면 앞으로 어떻게 살래?', isGood: false },
    { id: 165, user: 'User165', text: '오늘 하루도 고생 많았어요. 맛있는 거 먹고 푹 쉬어요!', isGood: false },
    { id: 166, user: 'User166', text: '이런 글 올릴 시간에 공부나 해라.', isGood: false },
    { id: 167, user: 'User167', text: '당신의 용기에 박수를 보냅니다.', isGood: false },
    { id: 168, user: 'User168', text: '또 징징대네.', isGood: false },
    { id: 169, user: 'User169', text: '당신은 충분히 잘하고 있어요.', isGood: false },
    { id: 170, user: 'User170', text: '이런 글 그만 좀 써라.', isGood: false },
    { id: 171, user: 'User171', text: '오늘도 힘내요! 응원할게요.', isGood: false },
    { id: 172, user: 'User172', text: '관심받고 싶어서 이러는 거지?', isGood: false },
    { id: 173, user: 'User173', text: '당신의 하루가 더 좋아지길 바랍니다.', isGood: false },
    { id: 174, user: 'User174', text: '이런 글 볼 때마다 짜증난다.', isGood: false },
    { id: 175, user: 'User175', text: '당신은 혼자가 아니에요.', isGood: false },
    { id: 176, user: 'User176', text: '또 시작이네.', isGood: false },
    { id: 177, user: 'User177', text: '당신의 마음을 이해해요.', isGood: false },
    { id: 178, user: 'User178', text: '이런 글 올리지 마라.', isGood: false },
    { id: 179, user: 'User179', text: '당신의 용기가 멋져요.', isGood: false },
    { id: 180, user: 'User180', text: '누가 신경이나 쓴다고.', isGood: false },
    { id: 181, user: 'User181', text: '당신은 소중한 사람이에요.', isGood: false },
    { id: 182, user: 'User182', text: '또 징징거림?', isGood: false },
    { id: 183, user: 'User183', text: '당신의 이야기를 들어줄게요.', isGood: false },
    { id: 184, user: 'User184', text: '이런 글 올릴 시간에 일이나 해라.', isGood: false },
    { id: 185, user: 'User185', text: '당신의 존재가 큰 힘이 됩니다.', isGood: false },
    { id: 186, user: 'User186', text: '또 이런 글이네.', isGood: false },
    { id: 187, user: 'User187', text: '당신은 충분히 멋져요.', isGood: false },
    { id: 188, user: 'User188', text: '누가 신경이나 쓴다고 생각해?', isGood: false },
    { id: 189, user: 'User189', text: '당신의 하루가 행복하길.', isGood: false },
    { id: 190, user: 'User190', text: '이런 글 올릴 시간에 운동이나 해라.', isGood: false },
    { id: 191, user: 'User191', text: '당신은 혼자가 아니에요.', isGood: false },
    { id: 192, user: 'User192', text: '또 징징대네.', isGood: false },
    { id: 193, user: 'User193', text: '당신의 용기에 박수를 보냅니다.', isGood: false },
    { id: 194, user: 'User194', text: '이런 글 그만 좀 써라.', isGood: false },
    { id: 195, user: 'User195', text: '오늘도 힘내요! 응원할게요.', isGood: false },
    { id: 196, user: 'User196', text: '관심받고 싶어서 이러는 거지?', isGood: false },
    { id: 197, user: 'User197', text: '당신의 하루가 더 좋아지길 바랍니다.', isGood: false },
    { id: 198, user: 'User198', text: '이런 글 볼 때마다 짜증난다.', isGood: false },
    { id: 199, user: 'User199', text: '당신은 혼자가 아니에요.', isGood: false },
    { id: 200, user: 'User200', text: '또 시작이네.', isGood: false },
    { id: 201, user: 'User201', text: '당신의 마음을 이해해요.', isGood: false },
    { id: 202, user: 'User202', text: '이런 글 올리지 마라.', isGood: false },
    { id: 203, user: 'User203', text: '당신의 용기가 멋져요.', isGood: false },
    { id: 204, user: 'User204', text: '누가 신경이나 쓴다고.', isGood: false },
    { id: 205, user: 'User205', text: '당신은 소중한 사람이에요.', isGood: false },
    { id: 206, user: 'User206', text: '또 징징거림?', isGood: false },
    { id: 207, user: 'User207', text: '당신의 이야기를 들어줄게요.', isGood: false },
    { id: 208, user: 'User208', text: '이런 글 올릴 시간에 일이나 해라.', isGood: false },
    { id: 209, user: 'User209', text: '당신의 존재가 큰 힘이 됩니다.', isGood: false },
    { id: 210, user: 'User210', text: '또 이런 글이네.', isGood: false },
    { id: 211, user: 'User211', text: '당신은 충분히 멋져요.', isGood: false },
    { id: 212, user: 'User212', text: '누가 신경이나 쓴다고 생각해?', isGood: false },
    { id: 213, user: 'User213', text: '당신의 하루가 행복하길.', isGood: false },
    { id: 214, user: 'User214', text: '이런 글 올릴 시간에 운동이나 해라.', isGood: false },
    { id: 215, user: 'User215', text: '당신은 혼자가 아니에요.', isGood: false },
    { id: 216, user: 'User216', text: '또 징징대네.', isGood: false },
    { id: 217, user: 'User217', text: '당신의 용기에 박수를 보냅니다.', isGood: false },
    { id: 218, user: 'User218', text: '이런 글 그만 좀 써라.', isGood: false },
    { id: 219, user: 'User219', text: '오늘도 힘내요! 응원할게요.', isGood: false },
    { id: 220, user: 'User220', text: '관심받고 싶어서 이러는 거지?', isGood: false },
    { id: 221, user: 'User221', text: '당신의 하루가 더 좋아지길 바랍니다.', isGood: false },
    { id: 222, user: 'User222', text: '이런 글 볼 때마다 짜증난다.', isGood: false },
    { id: 223, user: 'User223', text: '당신은 혼자가 아니에요.', isGood: false },
    { id: 224, user: 'User224', text: '또 시작이네.', isGood: false },
    { id: 225, user: 'User225', text: '당신의 마음을 이해해요.', isGood: false },
    { id: 226, user: 'User226', text: '이런 글 올리지 마라.', isGood: false },
    { id: 227, user: 'User227', text: '당신의 용기가 멋져요.', isGood: false },
    { id: 228, user: 'User228', text: '누가 신경이나 쓴다고.', isGood: false },
    { id: 229, user: 'User229', text: '당신은 소중한 사람이에요.', isGood: false },
    { id: 230, user: 'User230', text: '또 징징거림?', isGood: false },
    { id: 231, user: 'User231', text: '당신의 이야기를 들어줄게요.', isGood: false },
    { id: 232, user: 'User232', text: '이런 글 올릴 시간에 일이나 해라.', isGood: false },
    { id: 233, user: 'User233', text: '당신의 존재가 큰 힘이 됩니다.', isGood: false },
    { id: 234, user: 'User234', text: '또 이런 글이네.', isGood: false },
    { id: 235, user: 'User235', text: '당신은 충분히 멋져요.', isGood: false },
    { id: 236, user: 'User236', text: '누가 신경이나 쓴다고 생각해?', isGood: false },
    { id: 237, user: 'User237', text: '당신의 하루가 행복하길.', isGood: false },
    { id: 238, user: 'User238', text: '이런 글 올릴 시간에 운동이나 해라.', isGood: false },
    { id: 239, user: 'User239', text: '당신은 혼자가 아니에요.', isGood: false },
    { id: 240, user: 'User240', text: '또 징징대네.', isGood: false },
    { id: 241, user: 'User241', text: '당신의 용기에 박수를 보냅니다.', isGood: false },
    { id: 242, user: 'User242', text: '이런 글 그만 좀 써라.', isGood: false },
    { id: 243, user: 'User243', text: '오늘도 힘내요! 응원할게요.', isGood: false },
    { id: 244, user: 'User244', text: '관심받고 싶어서 이러는 거지?', isGood: false },
    { id: 245, user: 'User245', text: '당신의 하루가 더 좋아지길 바랍니다.', isGood: false },
    { id: 246, user: 'User246', text: '이런 글 볼 때마다 짜증난다.', isGood: false },
    { id: 247, user: 'User247', text: '당신은 혼자가 아니에요.', isGood: false },
    { id: 248, user: 'User248', text: '또 시작이네.', isGood: false },
    { id: 249, user: 'User249', text: '당신의 마음을 이해해요.', isGood: false },
    { id: 250, user: 'User250', text: '이런 글 올리지 마라.', isGood: false },
    { id: 251, user: 'User251', text: '뭐 그런 걸로 힘들어하냐? 멘탈이 두부임?', isGood: false },
    { id: 252, user: 'User252', text: '힘내세요! 당신은 혼자가 아니에요. 주변에 좋은 사람들이 더 많을 거예요.', isGood: false },
    { id: 253, user: 'User253', text: '관심받고 싶어서 글 올렸네 ㅋㅋㅋ', isGood: false },
    { id: 254, user: 'User254', text: '이런 글 보기 싫다. 삭제 좀.', isGood: false },
    { id: 255, user: 'User255', text: '무슨 일인지는 모르겠지만, 분명 잘 해결될 거예요. 응원합니다!', isGood: false },
    { id: 256, user: 'User256', text: 'ㅋㅋㅋㅋㅋ 한심하다', isGood: false },
    { id: 257, user: 'User257', text: '당신의 존재는 그 자체로 소중해요. 잊지 마세요.', isGood: false },
    { id: 258, user: 'User258', text: '에휴...ㅉㅉ', isGood: false },
    { id: 259, user: 'User259', text: '이런 거 올릴 시간에 자기계발이나 더 하지?', isGood: false },
    { id: 260, user: 'User260', text: '따뜻한 차 한잔 하면서 마음을 진정시켜보세요. 괜찮아질 거예요.', isGood: false },
    { id: 261, user: 'User261', text: '다 너가 잘못해서 그런거 아님?', isGood: false },
    { id: 262, user: 'User262', text: '세상에는 당신의 행복을 바라는 사람들이 더 많아요.', isGood: false },
    { id: 263, user: 'User263', text: '울고싶을 때는 실컷 우는 것도 방법이에요. 감정을 억누르지 마세요.', isGood: false },
    { id: 264, user: 'User264', text: '그렇게 쉽게 상처받으면 앞으로 어떻게 살래?', isGood: false },
    { id: 265, user: 'User265', text: '오늘 하루도 고생 많았어요. 맛있는 거 먹고 푹 쉬어요!', isGood: false },
    { id: 266, user: 'User266', text: '이런 글 올릴 시간에 공부나 해라.', isGood: false },
    { id: 267, user: 'User267', text: '당신의 용기에 박수를 보냅니다.', isGood: false },
    { id: 268, user: 'User268', text: '또 징징대네.', isGood: false },
    { id: 269, user: 'User269', text: '당신은 충분히 잘하고 있어요.', isGood: false },
    { id: 270, user: 'User270', text: '이런 글 그만 좀 써라.', isGood: false },
    { id: 271, user: 'User271', text: '오늘도 힘내요! 응원할게요.', isGood: false },
    { id: 272, user: 'User272', text: '관심받고 싶어서 이러는 거지?', isGood: false },
    { id: 273, user: 'User273', text: '당신의 하루가 더 좋아지길 바랍니다.', isGood: false },
    { id: 274, user: 'User274', text: '이런 글 볼 때마다 짜증난다.', isGood: false },
    { id: 275, user: 'User275', text: '당신은 혼자가 아니에요.', isGood: false },
    { id: 276, user: 'User276', text: '또 시작이네.', isGood: false },
    { id: 277, user: 'User277', text: '당신의 마음을 이해해요.', isGood: false },
    { id: 278, user: 'User278', text: '이런 글 올리지 마라.', isGood: false },
    { id: 279, user: 'User279', text: '당신의 용기가 멋져요.', isGood: false },
    { id: 280, user: 'User280', text: '누가 신경이나 쓴다고.', isGood: false },
    { id: 281, user: 'User281', text: '당신은 소중한 사람이에요.', isGood: false },
    { id: 282, user: 'User282', text: '또 징징거림?', isGood: false },
    { id: 283, user: 'User283', text: '당신의 이야기를 들어줄게요.', isGood: false },
    { id: 284, user: 'User284', text: '이런 글 올릴 시간에 일이나 해라.', isGood: false },
    { id: 285, user: 'User285', text: '당신의 존재가 큰 힘이 됩니다.', isGood: false },
    { id: 286, user: 'User286', text: '또 이런 글이네.', isGood: false },
    { id: 287, user: 'User287', text: '당신은 충분히 멋져요.', isGood: false },
    { id: 288, user: 'User288', text: '누가 신경이나 쓴다고 생각해?', isGood: false },
    { id: 289, user: 'User289', text: '당신의 하루가 행복하길.', isGood: false },
    { id: 290, user: 'User290', text: '이런 글 올릴 시간에 운동이나 해라.', isGood: false },
    { id: 291, user: 'User291', text: '당신은 혼자가 아니에요.', isGood: false },
    { id: 292, user: 'User292', text: '또 징징대네.', isGood: false },
    { id: 293, user: 'User293', text: '당신의 용기에 박수를 보냅니다.', isGood: false },
    { id: 294, user: 'User294', text: '이런 글 그만 좀 써라.', isGood: false },
    { id: 295, user: 'User295', text: '오늘도 힘내요! 응원할게요.', isGood: false },
    { id: 296, user: 'User296', text: '관심받고 싶어서 이러는 거지?', isGood: false },
    { id: 297, user: 'User297', text: '당신의 하루가 더 좋아지길 바랍니다.', isGood: false },
    { id: 298, user: 'User298', text: '이런 글 볼 때마다 짜증난다.', isGood: false },
    { id: 299, user: 'User299', text: '당신은 혼자가 아니에요.', isGood: false },
    { id: 300, user: 'User300', text: '또 시작이네.', isGood: false },
    { id: 301, user: 'User301', text: '당신의 마음을 이해해요.', isGood: false },
    { id: 302, user: 'User302', text: '이런 글 올리지 마라.', isGood: false },
    { id: 303, user: 'User303', text: '당신의 용기가 멋져요.', isGood: false },
    { id: 304, user: 'User304', text: '누가 신경이나 쓴다고.', isGood: false },
    { id: 305, user: 'User305', text: '당신은 소중한 사람이에요.', isGood: false },
    { id: 306, user: 'User306', text: '또 징징거림?', isGood: false },
    { id: 307, user: 'User307', text: '당신의 이야기를 들어줄게요.', isGood: false },
    { id: 308, user: 'User308', text: '이런 글 올릴 시간에 일이나 해라.', isGood: false },
    { id: 309, user: 'User309', text: '당신의 존재가 큰 힘이 됩니다.', isGood: false },
    { id: 310, user: 'User310', text: '또 이런 글이네.', isGood: false },
    { id: 311, user: 'User311', text: '당신은 충분히 멋져요.', isGood: false },
    { id: 312, user: 'User312', text: '누가 신경이나 쓴다고 생각해?', isGood: false },
    { id: 313, user: 'User313', text: '당신의 하루가 행복하길.', isGood: false },
    { id: 314, user: 'User314', text: '이런 글 올릴 시간에 운동이나 해라.', isGood: false },
    { id: 315, user: 'User315', text: '당신은 혼자가 아니에요.', isGood: false },
    { id: 316, user: 'User316', text: '또 징징대네.', isGood: false },
    { id: 317, user: 'User317', text: '당신의 용기에 박수를 보냅니다.', isGood: false },
    { id: 318, user: 'User318', text: '이런 글 그만 좀 써라.', isGood: false },
    { id: 319, user: 'User319', text: '오늘도 힘내요! 응원할게요.', isGood: false },
    { id: 320, user: 'User320', text: '관심받고 싶어서 이러는 거지?', isGood: false },
    { id: 321, user: 'User321', text: '당신의 하루가 더 좋아지길 바랍니다.', isGood: false },
    { id: 322, user: 'User322', text: '이런 글 볼 때마다 짜증난다.', isGood: false },
    { id: 323, user: 'User323', text: '당신은 혼자가 아니에요.', isGood: false },
    { id: 324, user: 'User324', text: '또 시작이네.', isGood: false },
    { id: 325, user: 'User325', text: '당신의 마음을 이해해요.', isGood: false },
    { id: 326, user: 'User326', text: '이런 글 올리지 마라.', isGood: false },
    { id: 327, user: 'User327', text: '당신의 용기가 멋져요.', isGood: false },
    { id: 328, user: 'User328', text: '누가 신경이나 쓴다고.', isGood: false },
    { id: 329, user: 'User329', text: '당신은 소중한 사람이에요.', isGood: false },
    { id: 330, user: 'User330', text: '또 징징거림?', isGood: false },
    { id: 331, user: 'User331', text: '당신의 이야기를 들어줄게요.', isGood: false },
    { id: 332, user: 'User332', text: '이런 글 올릴 시간에 일이나 해라.', isGood: false },
    { id: 333, user: 'User333', text: '당신의 존재가 큰 힘이 됩니다.', isGood: false },
    { id: 334, user: 'User334', text: '또 이런 글이네.', isGood: false },
    { id: 335, user: 'User335', text: '당신은 충분히 멋져요.', isGood: false },
    { id: 336, user: 'User336', text: '누가 신경이나 쓴다고 생각해?', isGood: false },
    { id: 337, user: 'User337', text: '당신의 하루가 행복하길.', isGood: false },
    { id: 338, user: 'User338', text: '이런 글 올릴 시간에 운동이나 해라.', isGood: false },
    { id: 339, user: 'User339', text: '당신은 혼자가 아니에요.', isGood: false },
    { id: 340, user: 'User340', text: '또 징징대네.', isGood: false },
    { id: 341, user: 'User341', text: '당신의 용기에 박수를 보냅니다.', isGood: false },
    { id: 342, user: 'User342', text: '이런 글 그만 좀 써라.', isGood: false },
    { id: 343, user: 'User343', text: '오늘도 힘내요! 응원할게요.', isGood: false },
    { id: 344, user: 'User344', text: '관심받고 싶어서 이러는 거지?', isGood: false },
    { id: 345, user: 'User345', text: '당신의 하루가 더 좋아지길 바랍니다.', isGood: false },
    { id: 346, user: 'User346', text: '이런 글 볼 때마다 짜증난다.', isGood: false },
    { id: 347, user: 'User347', text: '당신은 혼자가 아니에요.', isGood: false },
    { id: 348, user: 'User348', text: '또 시작이네.', isGood: false },
    { id: 349, user: 'User349', text: '당신의 마음을 이해해요.', isGood: false },
    { id: 350, user: 'User350', text: '이런 글 올리지 마라.', isGood: false },
    { id: 351, user: 'User351', text: '뭐 그런 걸로 힘들어하냐? 멘탈이 두부임?', isGood: false },
    { id: 352, user: 'User352', text: '힘내세요! 당신은 혼자가 아니에요. 주변에 좋은 사람들이 더 많을 거예요.', isGood: false },
    { id: 353, user: 'User353', text: '관심받고 싶어서 글 올렸네 ㅋㅋㅋ', isGood: false },
    { id: 354, user: 'User354', text: '이런 글 보기 싫다. 삭제 좀.', isGood: false },
    { id: 355, user: 'User355', text: '무슨 일인지는 모르겠지만, 분명 잘 해결될 거예요. 응원합니다!', isGood: false },
    { id: 356, user: 'User356', text: 'ㅋㅋㅋㅋㅋ 한심하다', isGood: false },
    { id: 357, user: 'User357', text: '당신의 존재는 그 자체로 소중해요. 잊지 마세요.', isGood: false },
    { id: 358, user: 'User358', text: '에휴...ㅉㅉ', isGood: false },
    { id: 359, user: 'User359', text: '이런 거 올릴 시간에 자기계발이나 더 하지?', isGood: false },
    { id: 360, user: 'User360', text: '따뜻한 차 한잔 하면서 마음을 진정시켜보세요. 괜찮아질 거예요.', isGood: false },
    { id: 361, user: 'User361', text: '다 너가 잘못해서 그런거 아님?', isGood: false },
    { id: 362, user: 'User362', text: '세상에는 당신의 행복을 바라는 사람들이 더 많아요.', isGood: false },
    { id: 363, user: 'User363', text: '울고싶을 때는 실컷 우는 것도 방법이에요. 감정을 억누르지 마세요.', isGood: false },
    { id: 364, user: 'User364', text: '그렇게 쉽게 상처받으면 앞으로 어떻게 살래?', isGood: false },
    { id: 365, user: 'User365', text: '오늘 하루도 고생 많았어요. 맛있는 거 먹고 푹 쉬어요!', isGood: false },
    { id: 366, user: 'User366', text: '이런 글 올릴 시간에 공부나 해라.', isGood: false },
    { id: 367, user: 'User367', text: '당신의 용기에 박수를 보냅니다.', isGood: false },
    { id: 368, user: 'User368', text: '또 징징대네.', isGood: false },
    { id: 369, user: 'User369', text: '당신은 충분히 잘하고 있어요.', isGood: false },
    { id: 370, user: 'User370', text: '이런 글 그만 좀 써라.', isGood: false },
    { id: 371, user: 'User371', text: '오늘도 힘내요! 응원할게요.', isGood: false },
    { id: 372, user: 'User372', text: '관심받고 싶어서 이러는 거지?', isGood: false },
    { id: 373, user: 'User373', text: '당신의 하루가 더 좋아지길 바랍니다.', isGood: false },
    { id: 374, user: 'User374', text: '이런 글 볼 때마다 짜증난다.', isGood: false },
    { id: 375, user: 'User375', text: '당신은 혼자가 아니에요.', isGood: false },
    { id: 376, user: 'User376', text: '또 시작이네.', isGood: false },
    { id: 377, user: 'User377', text: '당신의 마음을 이해해요.', isGood: false },
    { id: 378, user: 'User378', text: '이런 글 올리지 마라.', isGood: false },
    { id: 379, user: 'User379', text: '당신의 용기가 멋져요.', isGood: false },
    { id: 380, user: 'User380', text: '누가 신경이나 쓴다고.', isGood: false },
    { id: 381, user: 'User381', text: '당신은 소중한 사람이에요.', isGood: false },
    { id: 382, user: 'User382', text: '또 징징거림?', isGood: false },
    { id: 383, user: 'User383', text: '당신의 이야기를 들어줄게요.', isGood: false },
    { id: 384, user: 'User384', text: '이런 글 올릴 시간에 일이나 해라.', isGood: false },
    { id: 385, user: 'User385', text: '당신의 존재가 큰 힘이 됩니다.', isGood: false },
    { id: 386, user: 'User386', text: '또 이런 글이네.', isGood: false },
    { id: 387, user: 'User387', text: '당신은 충분히 멋져요.', isGood: false },
    { id: 388, user: 'User388', text: '누가 신경이나 쓴다고 생각해?', isGood: false },
    { id: 389, user: 'User389', text: '당신의 하루가 행복하길.', isGood: false },
    { id: 390, user: 'User390', text: '이런 글 올릴 시간에 운동이나 해라.', isGood: false },
    { id: 391, user: 'User391', text: '당신은 혼자가 아니에요.', isGood: false },
    { id: 392, user: 'User392', text: '또 징징대네.', isGood: false },
    { id: 393, user: 'User393', text: '당신의 용기에 박수를 보냅니다.', isGood: false },
    { id: 394, user: 'User394', text: '이런 글 그만 좀 써라.', isGood: false },
    { id: 395, user: 'User395', text: '오늘도 힘내요! 응원할게요.', isGood: false },
    { id: 396, user: 'User396', text: '관심받고 싶어서 이러는 거지?', isGood: false },
    { id: 397, user: 'User397', text: '당신의 하루가 더 좋아지길 바랍니다.', isGood: false },
    { id: 398, user: 'User398', text: '이런 글 볼 때마다 짜증난다.', isGood: false },
    { id: 399, user: 'User399', text: '당신은 혼자가 아니에요.', isGood: false },
    { id: 400, user: 'User400', text: '또 시작이네.', isGood: false },
    { id: 401, user: 'User401', text: '당신의 마음을 이해해요.', isGood: false },
    { id: 402, user: 'User402', text: '이런 글 올리지 마라.', isGood: false },
    { id: 403, user: 'User403', text: '당신의 용기가 멋져요.', isGood: false },
    { id: 404, user: 'User404', text: '누가 신경이나 쓴다고.', isGood: false },
    { id: 405, user: 'User405', text: '당신은 소중한 사람이에요.', isGood: false },
    { id: 406, user: 'User406', text: '또 징징거림?', isGood: false },
    { id: 407, user: 'User407', text: '당신의 이야기를 들어줄게요.', isGood: false },
    { id: 408, user: 'User408', text: '이런 글 올릴 시간에 일이나 해라.', isGood: false },
    { id: 409, user: 'User409', text: '당신의 존재가 큰 힘이 됩니다.', isGood: false },
    { id: 410, user: 'User410', text: '또 이런 글이네.', isGood: false },
    { id: 411, user: 'User411', text: '당신은 충분히 멋져요.', isGood: false },
    { id: 412, user: 'User412', text: '누가 신경이나 쓴다고 생각해?', isGood: false },
    { id: 413, user: 'User413', text: '당신의 하루가 행복하길.', isGood: false },
    { id: 414, user: 'User414', text: '이런 글 올릴 시간에 운동이나 해라.', isGood: false },
    { id: 415, user: 'User415', text: '당신은 혼자가 아니에요.', isGood: false },
    { id: 416, user: 'User416', text: '또 징징대네.', isGood: false },
    { id: 417, user: 'User417', text: '당신의 용기에 박수를 보냅니다.', isGood: false },
    { id: 418, user: 'User418', text: '이런 글 그만 좀 써라.', isGood: false },
    { id: 419, user: 'User419', text: '오늘도 힘내요! 응원할게요.', isGood: false },
    { id: 420, user: 'User420', text: '관심받고 싶어서 이러는 거지?', isGood: false },
    { id: 421, user: 'User421', text: '당신의 하루가 더 좋아지길 바랍니다.', isGood: false },
    { id: 422, user: 'User422', text: '이런 글 볼 때마다 짜증난다.', isGood: false },
    { id: 423, user: 'User423', text: '당신은 혼자가 아니에요.', isGood: false },
    { id: 424, user: 'User424', text: '또 시작이네.', isGood: false },
    { id: 425, user: 'User425', text: '당신의 마음을 이해해요.', isGood: false },
    { id: 426, user: 'User426', text: '이런 글 올리지 마라.', isGood: false },
    { id: 427, user: 'User427', text: '당신의 용기가 멋져요.', isGood: false },
    { id: 428, user: 'User428', text: '누가 신경이나 쓴다고.', isGood: false },
    { id: 429, user: 'User429', text: '당신은 소중한 사람이에요.', isGood: false },
    { id: 430, user: 'User430', text: '또 징징거림?', isGood: false },
    { id: 431, user: 'User431', text: '당신의 이야기를 들어줄게요.', isGood: false },
    { id: 432, user: 'User432', text: '이런 글 올릴 시간에 일이나 해라.', isGood: false },
    { id: 433, user: 'User433', text: '당신의 존재가 큰 힘이 됩니다.', isGood: false },
    { id: 434, user: 'User434', text: '또 이런 글이네.', isGood: false },
    { id: 435, user: 'User435', text: '당신은 충분히 멋져요.', isGood: false },
    { id: 436, user: 'User436', text: '누가 신경이나 쓴다고 생각해?', isGood: false },
    { id: 437, user: 'User437', text: '당신의 하루가 행복하길.', isGood: false },
    { id: 438, user: 'User438', text: '이런 글 올릴 시간에 운동이나 해라.', isGood: false },
    { id: 439, user: 'User439', text: '당신은 혼자가 아니에요.', isGood: false },
    { id: 440, user: 'User440', text: '또 징징대네.', isGood: false },
    { id: 441, user: 'User441', text: '당신의 용기에 박수를 보냅니다.', isGood: false },
    { id: 442, user: 'User442', text: '이런 글 그만 좀 써라.', isGood: false },
    { id: 443, user: 'User443', text: '오늘도 힘내요! 응원할게요.', isGood: false },
    { id: 444, user: 'User444', text: '관심받고 싶어서 이러는 거지?', isGood: false },
    { id: 445, user: 'User445', text: '당신의 하루가 더 좋아지길 바랍니다.', isGood: false },
    { id: 446, user: 'User446', text: '이런 글 볼 때마다 짜증난다.', isGood: false },
    { id: 447, user: 'User447', text: '당신은 혼자가 아니에요.', isGood: false },
    { id: 448, user: 'User448', text: '또 시작이네.', isGood: false },
    { id: 449, user: 'User449', text: '당신의 마음을 이해해요.', isGood: false },
    { id: 450, user: 'User450', text: '이런 글 올리지 마라.', isGood: false },
    { id: 451, user: 'User451', text: '뭐 그런 걸로 힘들어하냐? 멘탈이 두부임?', isGood: false },
    { id: 452, user: 'User452', text: '힘내세요! 당신은 혼자가 아니에요. 주변에 좋은 사람들이 더 많을 거예요.', isGood: false },
    { id: 453, user: 'User453', text: '관심받고 싶어서 글 올렸네 ㅋㅋㅋ', isGood: false },
    { id: 454, user: 'User454', text: '이런 글 보기 싫다. 삭제 좀.', isGood: false },
    { id: 455, user: 'User455', text: '무슨 일인지는 모르겠지만, 분명 잘 해결될 거예요. 응원합니다!', isGood: false },
    { id: 456, user: 'User456', text: 'ㅋㅋㅋㅋㅋ 한심하다', isGood: false },
    { id: 457, user: 'User457', text: '당신의 존재는 그 자체로 소중해요. 잊지 마세요.', isGood: false },
    { id: 458, user: 'User458', text: '에휴...ㅉㅉ', isGood: false },
    { id: 459, user: 'User459', text: '이런 거 올릴 시간에 자기계발이나 더 하지?', isGood: false },
    { id: 460, user: 'User460', text: '따뜻한 차 한잔 하면서 마음을 진정시켜보세요. 괜찮아질 거예요.', isGood: false },
    { id: 461, user: 'User461', text: '다 너가 잘못해서 그런거 아님?', isGood: false },
    { id: 462, user: 'User462', text: '세상에는 당신의 행복을 바라는 사람들이 더 많아요.', isGood: false },
    { id: 463, user: 'User463', text: '울고싶을 때는 실컷 우는 것도 방법이에요. 감정을 억누르지 마세요.', isGood: false },
    { id: 464, user: 'User464', text: '그렇게 쉽게 상처받으면 앞으로 어떻게 살래?', isGood: false },
    { id: 465, user: 'User465', text: '오늘 하루도 고생 많았어요. 맛있는 거 먹고 푹 쉬어요!', isGood: false },
    { id: 466, user: 'User466', text: '이런 글 올릴 시간에 공부나 해라.', isGood: false },
    { id: 467, user: 'User467', text: '당신의 용기에 박수를 보냅니다.', isGood: false },
    { id: 468, user: 'User468', text: '또 징징대네.', isGood: false },
    { id: 469, user: 'User469', text: '당신은 충분히 잘하고 있어요.', isGood: false },
    { id: 470, user: 'User470', text: '이런 글 그만 좀 써라.', isGood: false },
    { id: 471, user: 'User471', text: '오늘도 힘내요! 응원할게요.', isGood: false },
    { id: 472, user: 'User472', text: '관심받고 싶어서 이러는 거지?', isGood: false },
    { id: 473, user: 'User473', text: '당신의 하루가 더 좋아지길 바랍니다.', isGood: false },
    { id: 474, user: 'User474', text: '이런 글 볼 때마다 짜증난다.', isGood: false },
    { id: 475, user: 'User475', text: '당신은 혼자가 아니에요.', isGood: false },
    { id: 476, user: 'User476', text: '또 시작이네.', isGood: false },
    { id: 477, user: 'User477', text: '당신의 마음을 이해해요.', isGood: false },
    { id: 478, user: 'User478', text: '이런 글 올리지 마라.', isGood: false },
    { id: 479, user: 'User479', text: '당신의 용기가 멋져요.', isGood: false },
    { id: 480, user: 'User480', text: '누가 신경이나 쓴다고.', isGood: false },
    { id: 481, user: 'User481', text: '당신은 소중한 사람이에요.', isGood: false },
    { id: 482, user: 'User482', text: '또 징징거림?', isGood: false },
    { id: 483, user: 'User483', text: '당신의 이야기를 들어줄게요.', isGood: false },
    { id: 484, user: 'User484', text: '이런 글 올릴 시간에 일이나 해라.', isGood: false },
    { id: 485, user: 'User485', text: '당신의 존재가 큰 힘이 됩니다.', isGood: false },
    { id: 486, user: 'User486', text: '또 이런 글이네.', isGood: false },
    { id: 487, user: 'User487', text: '당신은 충분히 멋져요.', isGood: false },
    { id: 488, user: 'User488', text: '누가 신경이나 쓴다고 생각해?', isGood: false },
    { id: 489, user: 'User489', text: '당신의 하루가 행복하길.', isGood: false },
    { id: 490, user: 'User490', text: '이런 글 올릴 시간에 운동이나 해라.', isGood: false },
    { id: 491, user: 'User491', text: '당신은 혼자가 아니에요.', isGood: false },
    { id: 492, user: 'User492', text: '또 징징대네.', isGood: false },
    { id: 493, user: 'User493', text: '당신의 용기에 박수를 보냅니다.', isGood: false },
    { id: 494, user: 'User494', text: '이런 글 그만 좀 써라.', isGood: false },
    { id: 495, user: 'User495', text: '오늘도 힘내요! 응원할게요.', isGood: false },
    { id: 496, user: 'User496', text: '관심받고 싶어서 이러는 거지?', isGood: false },
    { id: 497, user: 'User497', text: '당신의 하루가 더 좋아지길 바랍니다.', isGood: false },
    { id: 498, user: 'User498', text: '이런 글 볼 때마다 짜증난다.', isGood: false },
    { id: 499, user: 'User499', text: '당신은 혼자가 아니에요.', isGood: false },
    { id: 500, user: 'User500', text: '또 시작이네.', isGood: false },
  ]
}; 