export const postData = {
  user: {
    name: "익명의 사용자",
    avatar: "https://via.placeholder.com/150/000000/FFFFFF/?text=User",
  },
  content: "오늘 정말 최악의 하루였어... 무슨 말을 해야 할지 모르겠다.",
  comments: [
    {
      id: 1,
      user: "user123",
      text: "또 관심받으려고 하는 거야?",
      isGood: false,
    },
    {
      id: 2,
      user: "hater456",
      text: "매일매일 불행하다고 하네 ㅋㅋ",
      isGood: false,
    },
    { id: 3, user: "toxic789", text: "그냥 SNS 그만해", isGood: false },
    {
      id: 4,
      user: "rude012",
      text: "뭐가 그렇게 힘드냐? 철없네",
      isGood: false,
    },
    {
      id: 5,
      user: "cynic345",
      text: "어차피 내일 되면 까먹을 텐데",
      isGood: false,
    },
    { id: 6, user: "annoyed678", text: "아 이런 글 보기 싫어", isGood: false },
    {
      id: 7,
      user: "dismissive901",
      text: "진짜 별거 아닌 일로 난리네",
      isGood: false,
    },
    { id: 8, user: "bully234", text: "관종이네 ㅋㅋㅋ", isGood: false },
    { id: 9, user: "complainer567", text: "이런 글 올리지 마", isGood: false },
    { id: 10, user: "judgemental890", text: "성격 문제 아님?", isGood: false },
    {
      id: 11,
      user: "indifferent123",
      text: "그래서 뭘 어쩌라고?",
      isGood: false,
    },
    {
      id: 12,
      user: "frustrated456",
      text: "맨날 힘들다고만 하네",
      isGood: false,
    },
    {
      id: 13,
      user: "fake_positive789",
      text: "좀 긍정적으로 살아봐",
      isGood: false,
    },
    { id: 14, user: "harsh012", text: "약한 놈", isGood: false },
    {
      id: 15,
      user: "sarcastic345",
      text: "그럼 SNS 하지 말고 일기나 써",
      isGood: false,
    },
    {
      id: 16,
      user: "pointless678",
      text: "이런 글 올려서 뭐가 달라지냐",
      isGood: false,
    },
    { id: 17, user: "bitter901", text: "우울함 팔이 하네", isGood: false },
    {
      id: 18,
      user: "curious_meanie234",
      text: "뭔 일인지도 안 말하면서",
      isGood: false,
    },
    { id: 19, user: "minimizer567", text: "오버하지 마", isGood: false },
    {
      id: 20,
      user: "comparison890",
      text: "남들은 더 힘들게 사는데",
      isGood: false,
    },
    { id: 21, user: "selfish123", text: "자기만 힘든 줄 아냐", isGood: false },
    {
      id: 22,
      user: "mental_critic456",
      text: "멘탈 약하네 진짜",
      isGood: false,
    },
    { id: 23, user: "delete_demander789", text: "그냥 자삭해", isGood: false },
    { id: 24, user: "unwanted012", text: "누가 물어봤냐", isGood: false },
    { id: 25, user: "mockery345", text: "ㅋㅋㅋ 웃기네", isGood: false },
    {
      id: 26,
      user: "work_blamer678",
      text: "일 좀 제대로 하면 안 그럴 텐데",
      isGood: false,
    },
    {
      id: 27,
      user: "age_shamer901",
      text: "어른이면서 왜 이래",
      isGood: false,
    },
    { id: 28, user: "victim_blamer234", text: "피해의식 쩌네", isGood: false },
    {
      id: 29,
      user: "tired_of_posts567",
      text: "그냥 쉬어 제발",
      isGood: false,
    },
    {
      id: 30,
      user: "blame_shifter890",
      text: "남 탓만 하지 말고",
      isGood: false,
    },
    { id: 31, user: "tmi_hater123", text: "TMI네 진짜", isGood: false },
    {
      id: 32,
      user: "trivializer456",
      text: "뭐 이딴 걸로 힘들어해",
      isGood: false,
    },
    {
      id: 33,
      user: "drama_critic789",
      text: "드라마 너무 많이 본 거 아냐",
      isGood: false,
    },
    {
      id: 34,
      user: "lazy_accuser012",
      text: "그냥 놀고먹고 싶다는 소리지",
      isGood: false,
    },
    {
      id: 35,
      user: "reality_checker345",
      text: "세상이 네 맘대로 되냐",
      isGood: false,
    },
    {
      id: 36,
      user: "contagious_anger678",
      text: "이런 글 보니까 내가 다 짜증나네",
      isGood: false,
    },
    {
      id: 37,
      user: "patience_demander901",
      text: "좀 참아봐 진짜",
      isGood: false,
    },
    {
      id: 38,
      user: "disinterested234",
      text: "아무도 안 궁금해",
      isGood: false,
    },
    {
      id: 39,
      user: "expectation_killer567",
      text: "그래서 우리한테 뭘 바라는 거임",
      isGood: false,
    },
    {
      id: 40,
      user: "shallow_thinker890",
      text: "생각이 너무 짧아",
      isGood: false,
    },
    {
      id: 41,
      user: "pattern_spotter123",
      text: "맨날 이런 식이네",
      isGood: false,
    },
    {
      id: 42,
      user: "solution_simplifier456",
      text: "그럼 안 하면 되잖아",
      isGood: false,
    },
    { id: 43, user: "busy_shamer789", text: "할 일 없나보네", isGood: false },
    {
      id: 44,
      user: "fitness_pusher012",
      text: "이런 글 쓸 시간에 운동이나 해",
      isGood: false,
    },
    {
      id: 45,
      user: "frustrated_reader345",
      text: "진짜 답답하네",
      isGood: false,
    },
    {
      id: 46,
      user: "isolation_advocate678",
      text: "그냥 혼자 끙끙 앓아",
      isGood: false,
    },
    {
      id: 47,
      user: "detail_demander901",
      text: "뭔 일인지 말은 해야지",
      isGood: false,
    },
    {
      id: 48,
      user: "sleepy_escaper234",
      text: "그냥 자야겠네 이거 보니까",
      isGood: false,
    },
    { id: 49, user: "tear_stopper567", text: "눈물 그만 닦고", isGood: false },
    {
      id: 50,
      user: "stress_minimizer890",
      text: "이런 걸로 스트레스받냐",
      isGood: false,
    },
    {
      id: 51,
      user: "hobby_suggester123",
      text: "그냥 취미나 만들어",
      isGood: false,
    },
    {
      id: 52,
      user: "mood_police456",
      text: "우울한 글 그만 써",
      isGood: false,
    },
    {
      id: 53,
      user: "fault_finder789",
      text: "네 잘못이겠지 뭐",
      isGood: false,
    },
    {
      id: 54,
      user: "life_critic012",
      text: "이런 식으로 살면 안 되는데",
      isGood: false,
    },
    {
      id: 55,
      user: "strength_demander345",
      text: "좀 더 강해져봐",
      isGood: false,
    },
    {
      id: 56,
      user: "conditional_helper678",
      text: "무슨 일인지 말해야 도와주지",
      isGood: false,
    },
    {
      id: 57,
      user: "social_fixer901",
      text: "그냥 친구들이랑 놀아",
      isGood: false,
    },
    { id: 58, user: "book_pusher234", text: "책이나 읽어", isGood: false },
    {
      id: 59,
      user: "solution_seeker567",
      text: "그래서 해결책은?",
      isGood: false,
    },
    {
      id: 60,
      user: "universal_sufferer890",
      text: "남들도 다 힘들어",
      isGood: false,
    },
    { id: 61, user: "maturity_teacher123", text: "좀 철들어", isGood: false },
    { id: 62, user: "endurance_advocate456", text: "그냥 참아", isGood: false },
    {
      id: 63,
      user: "topic_critic789",
      text: "뭐 이런 걸로 글을 써",
      isGood: false,
    },
    {
      id: 64,
      user: "deletion_suggester012",
      text: "그냥 자삭하고 자",
      isGood: false,
    },
    {
      id: 65,
      user: "repetition_spotter345",
      text: "또 시작이네",
      isGood: false,
    },
    {
      id: 66,
      user: "content_filter678",
      text: "이런 글 안 봤으면 좋겠어",
      isGood: false,
    },
    {
      id: 67,
      user: "effort_demander901",
      text: "좀 더 노력해봐",
      isGood: false,
    },
    { id: 68, user: "sleep_advisor234", text: "그냥 일찍 자", isGood: false },
    {
      id: 69,
      user: "pattern_analyst567",
      text: "매번 똑같은 패턴이네",
      isGood: false,
    },
    {
      id: 70,
      user: "boredom_accuser890",
      text: "심심하니까 이런 글 쓰는 거지",
      isGood: false,
    },
    {
      id: 71,
      user: "platform_quitter123",
      text: "그럼 SNS 안 하면 되잖아",
      isGood: false,
    },
    {
      id: 72,
      user: "fuss_minimizer456",
      text: "진짜 별일 아닌데 호들갑",
      isGood: false,
    },
    {
      id: 73,
      user: "curiosity_killer789",
      text: "뭔 일인지 궁금하지도 않아",
      isGood: false,
    },
    {
      id: 74,
      user: "forced_happiness012",
      text: "그냥 웃고 살아",
      isGood: false,
    },
    {
      id: 75,
      user: "energy_redirector345",
      text: "이런 글 쓸 에너지로 뭐라도 해봐",
      isGood: false,
    },
    {
      id: 76,
      user: "self_reliance678",
      text: "그냥 혼자 해결해",
      isGood: false,
    },
    {
      id: 77,
      user: "content_hater901",
      text: "아 진짜 이런 글 싫어",
      isGood: false,
    },
    {
      id: 78,
      user: "friend_redirector234",
      text: "그냥 친구한테 말해",
      isGood: false,
    },
    {
      id: 79,
      user: "drama_critic567",
      text: "뭔 일이길래 이렇게 호들갑",
      isGood: false,
    },
    {
      id: 80,
      user: "ignore_advocate890",
      text: "그냥 무시하고 살아",
      isGood: false,
    },
    {
      id: 81,
      user: "lifestyle_critic123",
      text: "그런 식으로 살면 안 되는데",
      isGood: false,
    },
    { id: 82, user: "maturity_pusher456", text: "좀 성숙해져", isGood: false },
    {
      id: 83,
      user: "learning_advocate789",
      text: "이런 글 올리는 시간에 뭐라도 배워",
      isGood: false,
    },
    {
      id: 84,
      user: "gaming_suggester012",
      text: "그냥 게임이나 해",
      isGood: false,
    },
    {
      id: 85,
      user: "context_demander345",
      text: "뭔 일인지 말은 해야 공감하지",
      isGood: false,
    },
    {
      id: 86,
      user: "attention_accuser678",
      text: "매번 이런 식으로 관심끌기",
      isGood: false,
    },
    {
      id: 87,
      user: "activity_pusher901",
      text: "좀 더 적극적으로 살아봐",
      isGood: false,
    },
    {
      id: 88,
      user: "exercise_advocate234",
      text: "그냥 운동해",
      isGood: false,
    },
    {
      id: 89,
      user: "content_stopper567",
      text: "이런 글 그만 써주면 안 될까",
      isGood: false,
    },
    {
      id: 90,
      user: "final_hater890",
      text: "진짜 짜증나네 이런 글",
      isGood: false,
    },
    {
      id: 91,
      user: "kind_friend123",
      text: "힘든 하루였구나... 괜찮아, 내일은 더 좋은 날이 될 거야 💕",
      isGood: true,
    },
    {
      id: 92,
      user: "supporter456",
      text: "무슨 일인지 모르겠지만 항상 응원하고 있어! 힘내 ❤️",
      isGood: true,
    },
    {
      id: 93,
      user: "caring_soul789",
      text: "가끔 그런 날이 있어. 충분히 쉬고 푹 자. 곧 지나갈 거야",
      isGood: true,
    },
    {
      id: 94,
      user: "always_there012",
      text: "말할 필요 없어. 그냥 옆에 있어줄게. 언제든 연락해",
      isGood: true,
    },
    {
      id: 95,
      user: "wise_comfort345",
      text: "힘든 하루도 네 삶의 소중한 일부야. 잘 버텨내고 있어",
      isGood: true,
    },
    {
      id: 96,
      user: "understanding678",
      text: "이런 감정을 표현하는 것도 용기가 필요한 일이야. 잘했어",
      isGood: true,
    },
    {
      id: 97,
      user: "we_are_here901",
      text: "혼자가 아니야. 우리가 있잖아. 천천히 털어놔도 돼",
      isGood: true,
    },
    {
      id: 98,
      user: "hope_giver234",
      text: "최악의 하루 뒤에는 더 좋은 날들이 기다리고 있어. 믿어줘",
      isGood: true,
    },
    {
      id: 99,
      user: "grateful_heart567",
      text: "감정을 솔직하게 표현해줘서 고마워. 네가 소중해",
      isGood: true,
    },
    {
      id: 100,
      user: "listening_ear890",
      text: "힘들 때 혼자 견디지 말고 언제든 말해. 들어줄게 🤗",
      isGood: true,
    },
  ],
};
